### PR TITLE
ADD: user variable to add his own modules

### LINKED ISSUE #17: Provide a way to add additionnal packages to specify own httpd_packages ?
Hi @robertdebock 
Once again, big thanks for all your collection, suc amazing roles here !

I would like to add more module in my httpd configuration and AFAICS https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_variables.html#understanding-variable-precedence the httpd_packages of your role will mostly have the latest word in the 15 position.
I would propose to make httpd_packages join 2 variables, the minimal one and a new custom one available to setup for everyone.
What's your point of view?

### PR DESCRIPTION
**Pull request by flotho**
FIX #17

### CODE REVIEW

**Comment by flotho** [comment]
ping @robertdebock , PR available for review

**Comment by flotho** [comment]
Hi @robertdebock hope you're doing well,
any chance to have a review here?

**Comment by flotho** [comment]
Hi @robertdebock , I've updated my PR , let me know if you need more to handle #17

**Comment by robertdebock** [comment]
Looks good, let's wait for CI and merge on success.

**Comment by robertdebock** [comment]
Oh, a small failure. Since a couple of days, tasks not in `main.yml` must be prepended by the stem of the filename.

So; tasks in `assert.yml` must have a `name` that starts with `assert | `. Something like this:

```yaml
- name: assert | Test something
  assert:
    that:
      # and so on.
```

Can you change that? If you don't have time, I can merge and fix later.

**Comment by robertdebock** [comment]
Let me merge the PR and fix that name forward.

**Comment by flotho** [comment]
Hi @robertdebock , thanks for your merge!
Thanks for your comments.
Honored to contribute to your awesome collection

**Pull request merged**
