### PR TITLE
Add httpd options directives and ssl vars

### PR DESCRIPTION
**Pull request by rilindo**
---
name: Options and SSL Updates
about: Added option directive and default ssl cert/keys variables:
---

**Describe the change**
- I needed to be able to allow file and directory browsing for an internal repo. To do this, I need to add the option directive as described [here](https://francescoficarola.com/apache-enable-files-directory-listing/). To do this, I simply updated the vhost template file to check to see if `options` key value exists and then write it out if it does.
.
- To get there, thought, I had to do some testing and during the run, it failed on `test httpd configuration validaty:
```
UNNING HANDLER [robertdebock.httpd : test httpd configuration validity] *******************************************************************************************************************************************
fatal: [rnode01]: FAILED! => {"changed": false, "cmd": ["httpd", "-t"], "delta": "0:00:00.255303", "end": "2020-06-20 21:03:12.751017", "msg": "non-zero return code", "rc": 1, "start": "2020-06-20 21:03:12.495714", "stderr": "[Sat Jun 20 21:03:12.720010 2020] [so:warn] [pid 19252] AH01574: module rewrite_module is already loaded, skipping\n[Sat Jun 20 21:03:12.720647 2020] [so:warn] [pid 19252] AH01574: module ssl_module is already loaded, skipping\nAH00526: Syntax error on line 11 of /etc/httpd/conf.d/ssl.conf:\nSSLCertificateFile: file '/etc/pki/tls/certs/apache-httpd.crt' does not exist or is empty", "stderr_lines": ["[Sat Jun 20 21:03:12.720010 2020] [so:warn] [pid 19252] AH01574: module rewrite_module is already loaded, skipping", "[Sat Jun 20 21:03:12.720647 2020] [so:warn] [pid 19252] AH01574: module ssl_module is already loaded, skipping", "AH00526: Syntax error on line 11 of /etc/httpd/conf.d/ssl.conf:", "SSLCertificateFile: file '/etc/pki/tls/certs/apache-httpd.crt' does not exist or is empty"], "stdout": "", "stdout_lines": []}
```
As it turns out, it  was looking for hard-coded cert and keys values [here](https://github.com/robertdebock/ansible-role-httpd/blob/46197f6cea968aee3c090804a44f0e50b43a93ed/templates/ssl.conf.j2#L9-L10), which is problematic as those file don't necessarily exist by default. So I created potentially variables with default values for the certificate and key files and substitute the hard-coded files with those variables.

**Testing**
In case a feature was added, how were tests performed?

No errors are found during the rule. Sites with and without options directive specified were created successfully and the httpd validation error did not crop up again:

```
TASK [robertdebock.bootstrap : wait for host] **********************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.bootstrap : test connection] ********************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.bootstrap : set bootstrap ansible_user] *********************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.bootstrap : gather ansible facts] ***************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.bootstrap : install bootstrap packages] *********************************************************************************************************************************************************
ok: [node01] => (item=python)
ok: [node01] => (item=sudo)

TASK [robertdebock.buildtools : install buildtools] ****************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.python_pip : install python pip] ****************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.python_pip : update pip] ************************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.python_pip : set pip alternatives] **************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.python_pip : configure pip proxy] ***************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.python_pip : trust hosts] ***********************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.python_pip : install requested modules] *********************************************************************************************************************************************************

TASK [robertdebock.httpd : install apache httpd] *******************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.httpd : modify selinux settings] ****************************************************************************************************************************************************************
ok: [node01] => (item=httpd_can_network_connect)

TASK [robertdebock.httpd : allow connections to custom port] *******************************************************************************************************************************************************
ok: [node01] => (item=80)
ok: [node01] => (item=443)

TASK [robertdebock.httpd : configure ssl] **************************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.httpd : configure locations] ********************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.httpd : configure vhosts] ***********************************************************************************************************************************************************************
ok: [node01] => (item=blog.dev.example.com)
ok: [node01] => (item=ks.example.com)
ok: [node01] => (item=repo.example.com)

TASK [robertdebock.httpd : configure httpd] ************************************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.httpd : configure listening ports] **************************************************************************************************************************************************************
skipping: [node01]

TASK [robertdebock.httpd : configure redirect from http to https] **************************************************************************************************************************************************
ok: [node01]

TASK [robertdebock.httpd : create docroot] *************************************************************************************************************************************************************************
ok: [node01] => (item={'name': 'blog.dev.example.com', 'servername': 'blog.dev.example.com', 'documentroot': '/var/www/vhosts/blog.dev.example.com'})
ok: [node01] => (item={'name': 'ks.example.com', 'servername': 'ks.example.com', 'documentroot': '/var/www/vhosts/ks.example.com'})
ok: [node01] => (item={'name': 'repo.example.com', 'servername': 'repo.example.com', 'options': '+Indexes +FollowSymLinks -MultiViews', 'documentroot': '/var/www/vhosts/repo.example.com'})

TASK [robertdebock.httpd : start and enable httpd] *****************************************************************************************************************************************************************
ok: [node01]

```

### CODE REVIEW

**Comment by robertdebock** [comment]
That's a great addition. Never needed the `options` so far, but completely logical.

The openssl certificate is generated by the openssl role, see `molecule/default/prepare.yml`. If you want to change the name of the certificate, you'd have to do that in 2 locations, `prepare.yml` and this role.

Can the `options` be a list, something like this?

```yaml
      httpd_vhosts:
￼        - name: docroot
￼          options:
            - "+Indexes"
            - "+FollowSymLinks"
            - "-MultiViews"
```

**Comment by rilindo** [comment]
I can do that! Regarding the openssl variables, do you mean this [prepare](https://github.com/robertdebock/ansible-role-openssl/blob/master/molecule/default/prepare.yml) file or this [file](https://github.com/robertdebock/ansible-role-httpd/blob/master/molecule/default/prepare.yml)

**Comment by rilindo** [comment]
Alright, the `options` update is done. I just need to add the `join` operator to convert incoming list to string. At this point, I just need some clarify on the ssl. I assume that once I added those certificate variables in the appropriate `prepare` files then the tests start passing?

**Comment by robertdebock** [comment]
### About the SSL Certificate:
In `molecule/default/prepare.yml` the openssl role is called to create a certificate. The httpd role "expects" the certificate already exists. So if you change the name of the certificate, both `prepare.yml` and `templates/ssl.conf` need to be changed.

For your PR, I would set this value in `defaults/main.yml`:
```yaml
# SSL Certificate:
￼httpd_openssl_crt: "{{ httpd_openssl_crt_directory }}/apache-httpd.crt"
￼
￼# SSL Key
￼httpd_openssl_key: "{{ httpd_openssl_key_directory }}/apache-httpd.key"
```

Remember that the `httpd_openssl_*_directory` is different per distribution, that's set in `vars/main.yml`.

### About the join:

You can use [loops in Jinja](https://jinja.palletsprojects.com/en/2.11.x/templates/#:~:text=Note%20that%2C%20in%20Python%2C%20else,the%20else%20keyword%20was%20chosen.&text=The%20loop%20variable%20always%20refers%20to%20the%20closest%20(innermost)%20loop.). Something like this: (untested)

```
{% if item.options is defined %}
￼   Options {% for option in item.options %}{{ option }}{% endfor %}
￼{% endif %}
￼```

Hope that helps!

**Comment by rilindo** [comment]
# About the Certificate
Good call. I made these the default:

```
# SSL Certificate:
httpd_openssl_crt: "{{ httpd_openssl_crt_directory }}/apache-httpd.crt"
# SSL Key
httpd_openssl_key: "{{ httpd_openssl_key_directory }}/apache-httpd.key"
```
And then changed the template like so:

```
    SSLCertificateFile "{{ httpd_openssl_crt }}"
    SSLCertificateKeyFile "{{ httpd_openssl_key }}"
```
And now all the tests has passed! Yay!

# About the join

Since it is a list though, I am wonder if there is any benefit of using a loop instead of just simply performing a conversion to a single string like so:

```
Options {{ item.options|join(' ') }}
```

Ultimately it is your project, though, so if you want a loop, I can re-write it to do a loop. 😄

**Comment by robertdebock** [comment]
Looks great, I'll merge and release a new version.

Thanks for you help @rilindo

**Pull request merged**
